# Generated by Django 3.1.2 on 2021-04-22 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material_synthesis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('timecost', models.DecimalField(decimal_places=7, default=0, max_digits=30, verbose_name='耗秒')),
                ('introduction', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('msystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_synthesis.msystem')),
            ],
            options={
                'verbose_name_plural': 'formulars',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('selling_price', models.DecimalField(decimal_places=4, default=0, max_digits=30, verbose_name='售价')),
                ('purchase_price', models.DecimalField(decimal_places=4, default=0, max_digits=30, verbose_name='进价')),
                ('timecost', models.DecimalField(decimal_places=7, default=0, max_digits=30, verbose_name='耗秒')),
                ('production_rate', models.DecimalField(decimal_places=7, default=0, max_digits=30, verbose_name='产速（个/秒）')),
                ('stock', models.DecimalField(decimal_places=7, default=0, max_digits=30, verbose_name='当前存量')),
                ('introduction', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('msystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_synthesis.msystem')),
            ],
            options={
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='Reactant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=7, default=0, max_digits=30, verbose_name='消耗数量')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('formular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_synthesis.formular')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_synthesis.item')),
            ],
            options={
                'verbose_name_plural': 'reactants',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=7, default=0, max_digits=30, verbose_name='生成数量')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('formular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_synthesis.formular')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_synthesis.item')),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
    ]
