# Generated by Django 3.1.2 on 2021-04-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_synthesis', '0002_formular_item_product_reactant'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_measure',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
