# Generated by Django 3.1.2 on 2021-04-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_synthesis', '0003_item_unit_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit_measure',
            field=models.CharField(default='', max_length=30),
        ),
    ]
