# Generated by Django 3.1.2 on 2021-04-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_synthesis', '0004_auto_20210423_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='introduction',
            field=models.TextField(default=''),
        ),
    ]
