# Generated by Django 3.1.2 on 2021-04-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_synthesis', '0005_auto_20210424_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='introduction',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_measure',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
