# Generated by Django 3.1.2 on 2021-04-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_synthesis', '0006_auto_20210424_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='msystem',
            name='maxno_products',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='msystem',
            name='maxno_reactants',
            field=models.IntegerField(default=5),
        ),
    ]
