# Generated by Django 3.1.2 on 2021-04-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_synthesis', '0007_auto_20210427_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='formular',
            name='f_products',
            field=models.ManyToManyField(related_name='products', through='material_synthesis.Product', to='material_synthesis.Item'),
        ),
        migrations.AddField(
            model_name='formular',
            name='f_reactants',
            field=models.ManyToManyField(related_name='reactants', through='material_synthesis.Reactant', to='material_synthesis.Item'),
        ),
    ]
