# Generated by Django 3.1.2 on 2021-05-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_synthesis', '0008_auto_20210428_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='msystem',
            name='default_products',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='msystem',
            name='default_reactants',
            field=models.IntegerField(default=5),
        ),
    ]
