# Generated by Django 3.1.2 on 2021-05-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='维度名')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='点名称')),
                ('linename', models.CharField(max_length=50, null=True, verbose_name='所属线名称')),
            ],
        ),
        migrations.CreateModel(
            name='PointDims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dotname', models.CharField(max_length=50, verbose_name='点名称')),
                ('dimension', models.CharField(max_length=20, verbose_name='维度')),
                ('dim_value', models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='值')),
            ],
        ),
    ]
