# Generated by Django 3.1.2 on 2021-05-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dxfc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointdims',
            name='dotname',
        ),
        migrations.AddField(
            model_name='point',
            name='dims',
            field=models.ManyToManyField(to='dxfc.PointDims'),
        ),
    ]
